# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Twenty"
license = "CCA 3.0"
licenselink = "html5up.net/license"
description = "Twenty Theme from html5up ported to hugo"
homepage = ""
tags = ["", ""]
features = ["responsive"]
min_version = 0.18

[author]
  name = "Tobias Bräutigam"
  homepage = "http://www.hirschberg-touristik.de"

# If porting an existing theme
[original]
  name = "ajlkn"
  homepage = "html5up.net"
  repo = ""
